name: Map Data Scraper

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 1 * * *" # This schedules the workflow to run every day at 1am.

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Python Script
        run: python main.py